build:
  version: "3.0"

cards:
  message: "Welcome to MyBank cards related to local APIs"
  contactDetails:
    name: "Jammy - Developer"
    email: "jammy@gmail.com"
  onCallSupport:
    -(020) 4545-8787
    -(020) 5454-3311